server:
  port: 5000


model:
  path: 'D:/Code/Python/final-project-deep-learning/tf_model/tf_model_052024_effecientNetB0_fruit.keras'
  drive_path: 'https://drive.google.com/uc?id=1nDbopiR_TTm9mT8u-2XMtNyljUbJ8RPt'
  class_names: ['apple', 'vanana', 'grape', 'mango', 'strawberry']
